version: '3'
services:
  flask:
    build: ./flaskapp
    ports:
      - "5000:5000"
    volumes:
      - ./flaskapp:/code
    restart: always
  postgis:
    image: kartoza/postgis
    volumes:
      - ./postgres_data:/var/lib/postgresql
    ports:
      - 5432:5432
    command: sh -c "echo \"host all all 0.0.0.0/0 md5\" >> /etc/postgresql/9.5/main/pg_hba.conf && /start-postgis.sh"

      